DROP DATABASE IF EXISTS QLCF
GO

CREATE DATABASE QLCF
GO

USE QLCF
GO

CREATE TABLE TaiKhoan
(
	ma INT IDENTITY PRIMARY KEY,
	tenDangNhap NVARCHAR(255) NOT NULL UNIQUE,
	matKhau NVARCHAR(255) NOT NULL,
	hoTen NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên',
	namSinh NVARCHAR(255) NOT NULL,
	SDT NVARCHAR(255) NOT NULL,
	gioiTinh NVARCHAR(255) NOT NULL DEFAULT N'Không xác định',
	trangThai BIT NOT NULL DEFAULT 1 -- tài khoảng đang hoạt động,
	--type int not null default 0
)
INSERT INTO TaiKhoan VALUES (N'admin', N'$2a$11$CxMrw9716vWAcPo6GQoNmOiNMGH/GOJ1P5tGeRTb4kpgcXguD1Vfi', N'Quản trị viên hệ thống', N'2000', N'18001091', N'Nam', 1);

CREATE TABLE Quyen 
(
	ma INT PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL,
)
INSERT INTO Quyen VALUES (1, N'Quản trị viên');
INSERT INTO Quyen VALUES (2, N'Quản lý');
INSERT INTO Quyen VALUES (3, N'Nhân viên');

CREATE TABLE PhanQuyen
(
	ma INT NOT NULL IDENTITY PRIMARY KEY,
	maTaiKhoan INT NOT NULL,
	maPhanQuyen INT NOT NULL,
	--PRIMARY KEY (maTaiKhoan,maPhanQuyen),
	FOREIGN KEY (maTaiKhoan) REFERENCES TaiKhoan(ma),
	FOREIGN KEY (maPhanQuyen) REFERENCES Quyen(ma),
)
INSERT INTO PhanQuyen VALUES (1, 1);

CREATE TABLE Ban
(
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên',
	trangThai BIT NOT NULL DEFAULT 1,
	CHECK (trangThai = 0 OR trangThai = 1)
)

CREATE TABLE LoaiMonAn
(
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên'
)
INSERT INTO LoaiMonAn VALUES (N'Nước giải khát');
INSERT INTO LoaiMonAn VALUES (N'Bánh ngọt');

CREATE TABLE DonVi
(
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên'
)
INSERT INTO DonVi VALUES (N'Ly');
INSERT INTO DonVi VALUES (N'Lon');
INSERT INTO DonVi VALUES (N'Chai');
INSERT INTO DonVi VALUES (N'Trái');
INSERT INTO DonVi VALUES (N'Cái');

CREATE TABLE MonAn
(
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên',
	maLoaiMonAn INT NOT NULL,
	gia MONEY NOT NULL DEFAULT 0,
	maDonVi INT NOT NULL,
	trangThai BIT NOT NULL,
	
	FOREIGN KEY (maDonVi) REFERENCES DonVi(ma),
	FOREIGN KEY (maLoaiMonAn) REFERENCES LoaiMonAn(ma)
)

CREATE TABLE Kho 
(
	ma INT PRIMARY KEY,
	tonKho INT NOT NULL DEFAULT 0,
	FOREIGN KEY (ma) REFERENCES MonAn(ma)
)

CREATE TABLE NguyenLieu (
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL,
	trongLuong FLOAT NOT NULL DEFAULT 0,
)

CREATE TABLE CongThuc(
	ma INT IDENTITY PRIMARY KEY,
	maMon INT NOT NULL,
	maNguyenLieu INT NOT NULL,
	chiPhi FLOAT NOT NULL DEFAULT 0,
	
	FOREIGN KEY (maMon) REFERENCES MonAn(ma),
	FOREIGN KEY (maNguyenLieu) REFERENCES NguyenLieu(ma),
)

CREATE TABLE PhieuNhap
(
	ma INT IDENTITY PRIMARY KEY,
	ngayNhap DATETIME NOT NULL DEFAULT GETDATE(),
	maKho INT NOT NULL,
	soLuong INT NOT NULL,
	giaDauVao MONEY NOT NULL,
	
	FOREIGN KEY (maKho) REFERENCES Kho(ma)
)

CREATE TABLE PhieuNhapNN
(
	ma INT IDENTITY PRIMARY KEY,
	ngayNhap DATETIME NOT NULL DEFAULT GETDATE(),
	maNguyenLieu INT NOT NULL,
	soLuong FLOAT NOT NULL,
	giaDauVao MONEY NOT NULL,

	FOREIGN KEY (maNguyenLieu) REFERENCES NguyenLieu(ma)
)

CREATE TABLE KhuyenMai
(
	ma INT IDENTITY PRIMARY KEY,
	ten NVARCHAR(255) NOT NULL DEFAULT N'Chưa đặt tên',
	maKhyenMai NVARCHAR(255) NOT NULL UNIQUE,
	tyLe FLOAT NOT NULL,
	trangThai BIT NOT NULL,
	CHECK (tyLe >= 0 AND tyLe <= 100)
)

CREATE TABLE HoaDon
(
	ma INT IDENTITY PRIMARY KEY,
	ngayVao DATETIME NOT NULL DEFAULT GETDATE(),
	ngayRa DATETIME,
	maBan INT NOT NULL,
	maKhuyenMai INT,
	trangThai BIT NOT NULL DEFAULT 0, -- 1 đã thanh toán ; 0 chưa thanh toán	
	
	FOREIGN KEY (maBan) REFERENCES Ban(ma),
	FOREIGN KEY (maKhuyenMai) REFERENCES KhuyenMai(ma)
)

CREATE TABLE CTHD
(
	ma INT IDENTITY PRIMARY KEY,
	maHoaDon INT NOT NULL,
	maMonAn INT NOT NULL,
	soLuong INT NOT NULL default 1,
	
	FOREIGN KEY (maHoaDon) REFERENCES HoaDon(ma),
	FOREIGN KEY (maMonAn) REFERENCES MonAn(ma)
)


